### ISSUE TITLE
TypeError: No loop matching the specified signature 

### ISSUE THREAD

**Issue by Kane-LAU** [samxuxiang/hnc-cad#1]
THANKS for your contribution！GREAT work~
But when i run the code below 
```
sh scripts/codebook.sh

```

something issue occured

![image](https://github.com/samxuxiang/hnc-cad/assets/42459125/0540dd98-926e-4271-b78c-66a4a3199c74)

how can i fix it ?

**Comment by samxuxiang** [comment]
I believe this is a tensorboard error for displaying the codebook usage in https://github.com/samxuxiang/hnc-cad/blob/d318fb85d8e5b88f451a0b59c5e9160a51ca6f02/codebook/train.py#L102 Try updating the tensorboard to the latest version, I tested it on 2.13.0 and there is no error.

**Comment by Kane-LAU** [comment]
i have updated tensorboard version,  same outputs . it seems  other reason @samxuxiang

**Comment by Kane-LAU** [comment]
> i have updated tensorboard version, same outputs . it seems other reason @samxuxiang

it's useful to change numpy version (ver1.24.4 --->1.23.5)

**Comment by samxuxiang** [comment]
Thank you for pointing out this issue!
